### ISSUE TITLE
Clarification needed?

### ISSUE THREAD

**Issue by typeshige** [goinnn/django-detect-cyclic#1]
Hi,

Trying to understand what you mean by:

```
js_info_dict = {
    'packages': ('your.app.package',),
}
```

I've been interested in trying this out as soon as I figure out what this is for and maybe a concrete example.

Thanks,
Shige

**Comment by goinnn** [comment]
You could understand it reading the [i18n documentation](https://docs.djangoproject.com/en/1.4/topics/i18n/translation/#module-django.views.i18n):

This is to translate the js files. If you want that django-detect-cyclic works quickly, code in your urls this:

```
js_info_dict = {
    'packages': ('django.conf',
                 'django.contrib.admin',
    ),
}
```

**Comment by goinnn** [comment]
If you need another thing..... tell me it

**Comment by typeshige** [comment]
Thanks, this helps a lot.  It might be a good idea to put that in the docs and maybe a few more examples for people who don't use i18n.

Also, is it required?  My projects support English only and I typically just remove everything having to do with i18n.

If it's not required, it might be nice to a note for those who don't use it?

Thanks again, I'll try this out as soon as I can.

**Comment by goinnn** [comment]
I thought that your project would support only English :-)

This is required for the wizard, I use the widgets of the admin site. I thought that it was required.

Please when you test the application, can you comment this [line](https://github.com/goinnn/django-detect-cyclic/blob/master/src/django_detect_cyclic/templates/detect_cyclic/detect_cyclic.html#L8) and do not code the js_info_dict in the urls, and tell me if the wizard has js errors? I think that is required but only for these widgets....

Thanks a lot!!

If you have another recommendation for me, please tell me

**Comment by typeshige** [comment]
Ok, I'll give it a test soon!
